services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=8192
      - TARGET=chrome
      - WXT_DEV_SERVER_PORT=3000
    command: sh -c "bun init && bun run build:chrome"
    # command: sleep infinity
